# Generated by Django 3.0.3 on 2020-02-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerlaunchapply',
            name='creator_department',
            field=models.CharField(blank=True, help_text='必填', max_length=64, verbose_name='创建人部门'),
        ),
        migrations.AddField(
            model_name='consumertrialapply',
            name='creator_department',
            field=models.CharField(blank=True, help_text='必填', max_length=64, verbose_name='创建人部门'),
        ),
        migrations.AddField(
            model_name='productlaunchapply',
            name='creator',
            field=models.CharField(blank=True, help_text='必填', max_length=64, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='productlaunchapply',
            name='creator_department',
            field=models.CharField(blank=True, help_text='必填', max_length=64, verbose_name='创建人部门'),
        ),
        migrations.AddField(
            model_name='productlaunchapply',
            name='creator_email',
            field=models.CharField(blank=True, help_text='必填', max_length=64, verbose_name='创建人邮箱'),
        ),
        migrations.AddField(
            model_name='productlaunchapply',
            name='creator_mobile',
            field=models.CharField(blank=True, help_text='必填', max_length=64, verbose_name='创建人手机号码'),
        ),
        migrations.AddField(
            model_name='vendorapiapply',
            name='creator',
            field=models.CharField(blank=True, help_text='必填', max_length=64, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='vendorapiapply',
            name='creator_department',
            field=models.CharField(blank=True, help_text='必填', max_length=64, verbose_name='创建人部门'),
        ),
        migrations.AddField(
            model_name='vendorapiapply',
            name='creator_email',
            field=models.CharField(blank=True, help_text='必填', max_length=64, verbose_name='创建人邮箱'),
        ),
        migrations.AddField(
            model_name='vendorapiapply',
            name='creator_mobile',
            field=models.CharField(blank=True, help_text='必填', max_length=64, verbose_name='创建人手机号码'),
        ),
        migrations.AddField(
            model_name='vendorapply',
            name='creator_department',
            field=models.CharField(blank=True, help_text='必填', max_length=64, verbose_name='创建人部门'),
        ),
        migrations.AlterField(
            model_name='consumerlaunchapply',
            name='org_number',
            field=models.CharField(blank=True, help_text='用于客户业务校核，客户的中英文名称应该与社会统一信用代码一致', max_length=128, verbose_name='社会统一信用代码/组织机构代码'),
        ),
        migrations.AlterField(
            model_name='consumertrialapply',
            name='org_number',
            field=models.CharField(blank=True, help_text='用于客户业务校核，客户的中英文名称应该与社会统一信用代码一致', max_length=128, verbose_name='社会统一信用代码/组织机构代码'),
        ),
    ]
