# Generated by Django 2.1.4 on 2020-03-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200304_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, help_text='审批中/审批通过/驳回/撤回/已生效/归档', max_length=32, verbose_name='工单状态'),
        ),
        migrations.AlterField(
            model_name='ticketflow',
            name='result',
            field=models.CharField(blank=True, help_text='同意/驳回', max_length=32, verbose_name='审批结果'),
        ),
    ]
