# Generated by Django 2.1.4 on 2020-03-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200304_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerorderapply',
            name='relate_code',
            field=models.CharField(blank=True, help_text='系统自动生成，用于绑定工单', max_length=128, verbose_name='关联代码'),
        ),
        migrations.AddField(
            model_name='consumerregisterapply',
            name='relate_code',
            field=models.CharField(blank=True, help_text='系统自动生成，用于绑定工单', max_length=128, verbose_name='关联代码'),
        ),
        migrations.AddField(
            model_name='consumertrialapply',
            name='relate_code',
            field=models.CharField(blank=True, help_text='系统自动生成，用于绑定工单', max_length=128, verbose_name='关联代码'),
        ),
        migrations.AddField(
            model_name='productlaunchapply',
            name='relate_code',
            field=models.CharField(blank=True, help_text='系统自动生成，用于绑定工单', max_length=128, verbose_name='关联代码'),
        ),
        migrations.AddField(
            model_name='vendorapiapply',
            name='relate_code',
            field=models.CharField(blank=True, help_text='系统自动生成，用于绑定工单', max_length=128, verbose_name='关联代码'),
        ),
        migrations.AddField(
            model_name='vendorapply',
            name='relate_code',
            field=models.CharField(blank=True, help_text='系统自动生成，用于绑定工单', max_length=128, verbose_name='关联代码'),
        ),
    ]
