# Generated by Django 2.1.4 on 2020-03-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200301_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='creator',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='creator_department',
            new_name='applicant_department',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='creator_job',
            new_name='applicant_job',
        ),
        migrations.AddField(
            model_name='ticket',
            name='relate_code',
            field=models.CharField(blank=True, help_text='系统自动生成，用于绑定申请记录', max_length=128, verbose_name='关联代码'),
        ),
    ]
