# Generated by Django 2.1.4 on 2020-03-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200302_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketflow',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ticketflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(blank=True, help_text='唯一标识', max_length=128, unique=True, verbose_name='工单号'),
        ),
    ]
