# Generated by Django 2.1.4 on 2020-03-04 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20200304_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='current_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_ticket_set', to=settings.AUTH_USER_MODEL, verbose_name='当前审批人'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintainer_ticket_set', to=settings.AUTH_USER_MODEL, verbose_name='维护人(责任人)'),
        ),
    ]
